export enum FightPropsEnum {
	MONEYLINE = "MONEYLINE",
    OU = "OU"
}

export enum FightStatus {
	ACTIVE = 'ACTIVE',
	CANCELED = 'CANCELED',
	COMPLETE = 'COMPLETE',
    FANTASY = 'FANTASY',
	PENDING = 'PENDING',
}

export enum Network {
	ESPN = 'ESPN',
	ESPNPLUS = 'ESPN+',
	HBO = 'HBO',
	HBOPPV = 'HBOPPV',
	DAZN = 'DAZN',
	SHOWTIME = 'SHOWTIME',
	SHOWTIMEPPV = 'SHOWTIMEPPV',
	FIGHTSYNC = 'FIGHTSYNC',
    FIGHTTV = 'FIGHTTV',
	NONE = 'NONE'
}

export enum ShowStatus {
	UPCOMING = 'PENDING',
    CANCELED = 'CANCELED',
	COMPLETE = 'COMPLETE',
	HISTORICAL = 'HISTORICAL'
}

export enum WeightClass {
	HEAVYWEIGHT = 'HEAVYWEIGHT',
	CRUISERWEIGHT = 'CRUISERWEIGHT',
	LIGHTHEAVYWEIGHT = 'LIGHTHEAVYWEIGHT',
	SUPERMIDDLEWEIGHT = 'SUPERMIDDLEWEIGHT',
	MIDDLEWEIGHT = 'MIDDLEWEIGHT',
	SUPERWELTERWEIGHT = 'SUPERWELTERWEIGHT',
	WELTERWEIGHT = 'WELTERWEIGHT',
	SUPERLIGHTWEIGHT = 'SUPERLIGHTWEIGHT',
	LIGHTWEIGHT = 'LIGHTWEIGHT',
	SUPERFEATHERWEIGHT = 'SUPERFEATHERWEIGHT',
	FEATHERWEIGHT = 'FEATHERWEIGHT',
	SUPERBANTAMWEIGHT = 'SUPERBANTAMWEIGHT',
	BANTAMWEIGHT = 'BANTAMWEIGHT',
	SUPERFLYWEIGHT = 'SUPERFLYWEIGHT',
	FLYWEIGHT = 'FLYWEIGHT',
	JRFLYWEIGHT = 'JRFLYWEIGHT'
}

export enum ReviewType {
	FANTASY = 'FANTASY',
	HISTORICAL = 'HISTORICAL',
	PREDICTION = 'PREDICTION',
	REVIEW = 'REVIEW',
}