export const officialList = [
    {
        "dq": 0,
        "draws": 0,
        "firstName": "terence",
        "home": "Omaha, NE",
        "kos": 30,
        "lastName": "crawford",
        "losses": 0,
        "ringname": "bud",
        "socials": [],
        "wins": 39,
        "profileImg": "https://res.cloudinary.com/dhen5jaym/image/upload/v1675693709/Terence_Crawford1.png_njqofk.webp",
        "id": "d49cfc85-c944-4023-96ed-4b7bf2772021"
    },
    {
        "dq": 0,
        "draws": 0,
        "firstName": "naoya",
        "home": "Yokohama, Japan",
        "kos": 21,
        "lastName": "inoue",
        "losses": 0,
        "ringname": "Monster",
        "socials": [],
        "wins": 24,
        "profileImg": "https://res.cloudinary.com/dhen5jaym/image/upload/v1675692801/Naoya_Inoue1.png_tj86y2.webp",
        "id": "6c01552d-6ed3-4d22-8d98-2cbef0ca8274"
    },
    {
        "dq": 0,
        "draws": 0,
        "firstName": "oleksandr",
        "home": "Oxnard, CA",
        "kos": 14,
        "lastName": "usyk",
        "losses": 0,
        "ringname": "The Cat",
        "socials": [],
        "wins": 21,
        "profileImg": "https://res.cloudinary.com/dhen5jaym/image/upload/v1675874008/Oleksander-Usyk.png_gz1ovh.webp",
        "id": "7e1ad803-9b71-4bbb-9e81-a11da61d75ca"
    },
    {
        "dq": 0,
        "draws": 2,
        "firstName": "saul",
        "home": "Guadalajara, Mexico",
        "kos": 39,
        "lastName": "alvarez",
        "losses": 2,
        "ringname": "canelo",
        "socials": [],
        "wins": 59,
        "profileImg": "https://res.cloudinary.com/dhen5jaym/image/upload/v1675695602/Canelo_Alvarez_g7jxt1.webp",
        "id": "5b3bbb72-71c2-4334-9972-1f82cb83bece"
    },
    {
        "dq": 0,
        "draws": 0,
        "firstName": "dmitry",
        "home": "Indio, CA",
        "kos": 11,
        "lastName": "bivol",
        "losses": 0,
        "ringname": "N/A",
        "socials": [],
        "updatedAt": {
          "$numberLong": "1651524412185"
        },
        "wins": 21,
        "profileImg": "https://res.cloudinary.com/dhen5jaym/image/upload/v1675694589/Dmitry_Bivol1.png_iftbrt.webp",
        "id": "0fcb1bd2-af7b-4b1d-9faa-85282850d7e8"
    },
    {
        "dq": 0,
        "draws": 0,
        "firstName": "devin",
        "home": "San Francisco, CA",
        "kos": 15,
        "lastName": "haney",
        "losses": 0,
        "ringname": "the dream",
        "socials": [],
        "updatedAt": {
          "$numberLong": "1653521649946"
        },
        "wins": 29,
        "profileImg": "https://res.cloudinary.com/dhen5jaym/image/upload/v1683050809/Devin_Haney1.png_tcxgoa.webp",
        "id": "0b0c844a-e0e7-400a-9f4b-302430b02b3e"
    },

    {
        "dq": 0,
        "draws": 0,
        "firstName": "shakur",
        "home": "Alexandria, VA",
        "kos": 10,
        "lastName": "stevenson",
        "losses": 0,
        "ringname": "Fearless",
        "socials": [],
        "wins": 20,
        "profileImg": "https://res.cloudinary.com/dhen5jaym/image/upload/v1680040343/Shakur_Stevenson1.png_wg2oys.webp",
        "id": "cee66597-adb5-4012-9cfa-05cbee29d2da"
    },
    {
        "dq": 0,
        "draws": 0,
        "firstName": "gervonta",
        "home": "Baltimore, MD",
        "kos": 26,
        "lastName": "davis",
        "losses": 0,
        "ringname": "Tank",
        "socials": [],
        "wins": 28,
        "profileImg": "https://res.cloudinary.com/dhen5jaym/image/upload/v1675691717/Gervonta_-Davis1.png_l1hd1b.webp",
        "id": "65a6b29e-9b3b-4bf5-903f-778e0d2dc351"
    },
    {
        "dq": 0,
        "draws": 1,
        "firstName": "tyson",
        "home": "Manchester, England",
        "kos": 24,
        "lastName": "fury",
        "losses": 0,
        "ringname": "The Gypsy King",
        "socials": [],
        "wins": 33,
        "profileImg": "https://res.cloudinary.com/dhen5jaym/image/upload/v1675693774/Tyson_Fury1.png_lzxgrb.webp",
        "id": "0ad9c579-1fd9-4d48-a4e1-cd620eaf6078"
    },
    {
        "dq": 0,
        "draws": 0,
        "firstName": "errol",
        "home": "Desoto, TX",
        "kos": 22,
        "lastName": "spence",
        "losses": 0,
        "ringname": "the truth",
        "socials": [],
        "wins": 28,
        "profileImg": "https://res.cloudinary.com/dhen5jaym/image/upload/v1687977658/Errol_Spence-Jr1.png_izfsk4.webp",
        "id": "4a15ff99-e30d-41b0-bde9-453a6e7f87c1"
    }
]
